name: Build Android APK (from ZIP)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip Flutter project
        run: |
          rm -rf app
          mkdir -p app
          unzip -o ejar_sanaa.zip -d app
          ls -la app
          ls -la app/ejar_sanaa

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.7"
          channel: stable
          cache: true

      - name: Configure Android (create android/ folder if missing)
        run: |
          cd app/ejar_sanaa
          flutter pub get
          flutter create . --platforms android

      - name: Build APK (Release)
        run: |
          cd app/ejar_sanaa
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ejar-sanaa-apk
          path: app/ejar_sanaa/build/app/outputs/flutter-apk/app-release.apk
